version: '3'
services:
  kibana-prod:
    image: lmenezes/cerebro:0.8.3
    ports:
      - 9000:9000
    networks:
      - elastic
    volumes:
      - ./.cerebro:/var/lib/cerebro
    command: '-Dconfig.file=/var/lib/cerebro/application.conf'

networks:
  elastic:
    driver: bridge
